version: "3.3"
services:
  valheim-server:
    image: "lloesche/valheim-server"
    container_name: "valheim-game-server"
    ports:
      - "2456-2457:2456-2457/udp"
      - "9000:9000/tcp"
      - "9001:9001/tcp"
    volumes:
      - "${PWD}/config:/config"
      - "${PWD}/data:/opt/valheim"
    env_file:
      - ".env"
    cap_add:
      - "sys_nice"
